version: "3.7"

services:
  rest:
    build:
      context: .
      target: prod
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    env_file:
      - tests/.env.test

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    env_file:
      - tests/.env.test
