version: "3"

services:
  rest-api:
    build:
      context: .
      target: prod
    
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    env_file:
      - .env

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb/data/db:/data/db
#    environment:
#      MONGO_INITDB_DATABASE: "icon"
#      MONGO_INITDB_ROOT_USERNAME: "mongo"
#      MONGO_INITDB_ROOT_PASSWORD: "changethis"
    env_file:
      - .env

